---
# ============================================================
# Atlassian Bitbucket Data Center
# ============================================================

# ------------------------------------------------------------
# Precheck
# ------------------------------------------------------------

- name: Run Bitbucket prechecks
  ansible.builtin.import_tasks: precheck.yml
  tags:
    - always
    - precheck

# ------------------------------------------------------------
# Prerequisites
# ------------------------------------------------------------

- name: Install Bitbucket prerequisites
  ansible.builtin.import_tasks: prerequisites.yml
  tags:
    - prerequisites

# ------------------------------------------------------------
# Install
# ------------------------------------------------------------

- name: Install Bitbucket
  ansible.builtin.import_tasks: install.yml
  tags:
    - install

# ------------------------------------------------------------
# Database
# ------------------------------------------------------------

- name: Validate Bitbucket database
  ansible.builtin.import_tasks: database.yml
  tags:
    - database

# ------------------------------------------------------------
# Configure
# ------------------------------------------------------------

- name: Configure Bitbucket
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configure

# ------------------------------------------------------------
# Cluster
# ------------------------------------------------------------

- name: Configure Bitbucket Data Center cluster
  ansible.builtin.import_tasks: cluster.yml
  when: bitbucket_clustered | bool
  tags:
    - cluster

# ------------------------------------------------------------
# Systemd
# ------------------------------------------------------------

- name: Configure Bitbucket systemd service
  ansible.builtin.import_tasks: systemd.yml
  tags:
    - systemd

# ------------------------------------------------------------
# Validate
# ------------------------------------------------------------

- name: Validate Bitbucket
  ansible.builtin.import_tasks: validate.yml
  tags:
    - validate
